### ISSUE TITLE
GGUF for Diffusers

### ISSUE THREAD

**Issue by al-swaiti** [city96/ComfyUI-GGUF#100]
do you planing to do this for diffusers ,,, here the  setup that made for bnb-NF4
 https://github.com/huggingface/diffusers/issues/9165
i think you can remove bnb-nf4 stuff and add gguf 
its features

**Comment by city96** [comment]
This would be an interesting thing to explore. Transformers [has gguf support](https://huggingface.co/docs/transformers/main/gguf) but it looks like it's just for loading and it gets converted back to FP16/FP32 on load instead of native inference? I'll look into it if I get the time.

**Comment by al-swaiti** [comment]
good luck ,,, already i responsible about more than 1000 students ,,, so excuse me if i was inactive ,, u know i'm ai physics teacher

**Comment by city96** [comment]
GGUF support has recently been merged into diffusers.

The page detailing how these can be used can be found here [here](https://huggingface.co/docs/diffusers/main/en/quantization/gguf)
