### ISSUE TITLE
How can I quantize my trained model into GGUF format? 

### ISSUE THREAD

**Issue by Lagrebanana** [city96/ComfyUI-GGUF#104]
I trained a model using the script from Kohya, using the Dreambooth method. How can I convert it to Q8?

**Comment by city96** [comment]
The readme in the [tools](https://github.com/city96/ComfyUI-GGUF/tree/main/tools) folder should have the step by step on how to convert it. Feel free to reopen this issue if you run into any problems.

**Comment by Lagrebanana** [comment]
thanks，it's work
