### ISSUE TITLE
comfyui-gguf fails to run on macOS Sequoia while it woked fine on macOS sonoma.

### ISSUE THREAD

**Issue by craii** [city96/ComfyUI-GGUF#108]
ComfyUI-GGUF works fine  on macOS sonoma. But after I upgrade mac to Sequoia, it fails. 

Reinstall comfyui-gguf, reinstall torch / numpy etc... all attemps fails.   

here is the log

/Users/eliascheung/Documents/ComfyUI/custom_nodes/ComfyUI-GGUF/nodes.py:79: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:212.)
  torch_tensor = torch.from_numpy(tensor.data) # mmap

ggml_sd_loader:
 1                             472
 2                             304
model weight dtype torch.bfloat16, manual cast: None
model_type FLOW
Requested to load Flux
Loading 1 new model
loaded completely 0.0 6456.9610595703125 True
  0%|                                                     | 0/4 [00:00<?, ?it/s]/AppleInternal/Library/BuildRoots/5a8a3fcc-55cb-11ef-848e-8a553ba56670/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:891: failed assertion `[MPSNDArray, initWithBufferImpl:offset:descriptor:isForNDArrayAlias:isUserBuffer:] Error: buffer is not large enough. Must be 63700992 bytes
'
/Users/eliascheung/anaconda3/lib/python3.11/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by city96** [comment]
Same issue as https://github.com/city96/ComfyUI-GGUF/issues/107 so tracking there, don't have any apple hardware so unlikely I'll be able to fix it but there's a pytorch issue/PR linked there that might.
