### ISSUE TITLE
(IMPORT FAILED)

### ISSUE THREAD

**Issue by eegneus** [city96/ComfyUI-GGUF#110]
(IMPORT FAILED): F:\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
TRY FIX -have to do this every time

**Comment by city96** [comment]
Could you provide some more information? What's the actual error for the import?

**Comment by eegneus** [comment]
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-09-21 10:04:58.322050
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]

F:\ComfyUI_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
PyTorch version 2.4.0+cu121 available.

 File "F:\ComfyUI_portable\ComfyUI\nodes.py", line 1994, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI-GGUF\__init__.py", line 7, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "F:\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 3, in <module>
    import gguf
ModuleNotFoundError: No module named 'gguf'
Cannot import F:\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI-GGUF module for custom nodes: No module named 'gguf'

[notice] A new release of pip is available: 24.0 -> 24.2

F:\ComfyUI_portable\python_embeded\Lib\site-packages\albumentations\__init__.py:13: UserWarning: A new version of Albumentations is available: 1.4.15 (you have 1.4.14). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()
F:\ComfyUI_portable\python_embeded\Lib\site-packages\vector_quantize_pytorch\vector_quantize_pytorch.py:462: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @autocast(enabled = False)
F:\ComfyUI_portable\python_embeded\Lib\site-packages\vector_quantize_pytorch\vector_quantize_pytorch.py:647: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @autocast(enabled = False)
F:\ComfyUI_portable\python_embeded\Lib\site-packages\vector_quantize_pytorch\finite_scalar_quantization.py:162: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @autocast(enabled = False)
F:\ComfyUI_portable\python_embeded\Lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
llama-cpp installed
Successfully installed py-cord[voice]

 0.0 seconds (IMPORT FAILED): F:\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI-GGUF

**Comment by eegneus** [comment]
decided, moved the folder 'gguf' from C:\...python311\site-packages\ to F:\ComfyUI_portable\...site-packages\

**Comment by city96** [comment]
Did you use the command from the readme to install the package? It shouldn't end up in your system env if you did. (The `-s` switch is important.)

```
.\python_embeded\python.exe -s -m pip install -r .\ComfyUI\custom_nodes\ComfyUI-GGUF\requirements.txt
```

**Comment by eegneus** [comment]
used without -s :(

**Comment by changlinniao** [comment]
I also encountered the same problem, the loading failed：
0.0 seconds (IMPORT FAILED): D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
