### ISSUE TITLE
Just generates noise

### ISSUE THREAD

**Issue by skelescene** [city96/ComfyUI-GGUF#111]
I'm not sure if this is just a workflow issue, but when I tried using this, it just outputs noise.
![2024-09-20_15-17](https://github.com/user-attachments/assets/9c89b571-7c98-4b09-8e21-9efde23aea2f)
Could I have some help?

**Comment by city96** [comment]
That looks like it should work.

The only thing I can point out is that using the gguf DualCLIP loader isn't actually required if you don't use a gguf text encoder model (which you aren't by the looks of it). Though when I replicate it 1:1 it seems to work even with that.

I guess maybe check the downloaded file(s) to make sure it's not a corrupt download?

![image](https://github.com/user-attachments/assets/da4a8d33-4e7b-483b-ac2a-c479aceab804)

**Comment by skelescene** [comment]
do

> That looks like it should work.
> 
> The only thing I can point out is that using the gguf DualCLIP loader isn't actually required if you don't use a gguf text encoder model (which you aren't by the looks of it). Though when I replicate it 1:1 it seems to work even with that.
> 
> I guess maybe check the downloaded file(s) to make sure it's not a corrupt download?
> 
> ![image](https://private-user-images.githubusercontent.com/125218114/369572053-da4a8d33-4e7b-483b-ac2a-c479aceab804.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NDc5NTQsIm5iZiI6MTcyNjk0NzY1NCwicGF0aCI6Ii8xMjUyMTgxMTQvMzY5NTcyMDUzLWRhNGE4ZDMzLTRlN2ItNDgzYi1hYzJhLWM0NzlhY2VhYjgwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQxOTQwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTE4MmU2NjQ4MzVmYTk4OGYwZGE1NDI1ODMyOGRlMGQwYzNjNzVhYzQzZWFkZDUwZGRhMDZiOGE3MDZkZTdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1U44zvE35vady_gS79LnQbavvMlN7mJ5nD4uy-GsbnU)

Do you have a download link for the clip_l and t5xxl_fp8e4m3fn files? I used the ones from here:
https://huggingface.co/comfyanonymous/flux_text_encoders/tree/main

**Comment by skelescene** [comment]
EDIT: So going down to the Q4_KS Model seemed to work! I think the Q5 model was just too much for my laptop haha

**Comment by city96** [comment]
You're using the right text encoders, so all good there. For the dual CLIP loader, I just meant that you should use the regular dual clip node and not the gguf dual clip one if you don't use any of the gguf T5 models from [here](https://huggingface.co/city96/t5-v1_1-xxl-encoder-gguf) (in other words, you're currently using the safetensor ones, so there's no need for the gguf specific node).

I think Q5 should work too since comfy can load a model partially, even if it doesn't fit fully on the GPU. Could just be a corrupt file/download as well, unless it really is something about that quant specifically.

Anyway, I'll close the issue for now though if anyone else runs into a similar issue we can reopen.

**Comment by JSoon** [comment]
Same problem here:
![image](https://github.com/user-attachments/assets/85b27e59-803b-4e76-81a9-2dfbe9722b02)

```
Device: Apple M1 Pro, macOS 14.5
UNet: flux1-dev-Q4_K_S.gguf
DualClip: t5-v1_1-xxl-encoder-Q5_K_M.gguf, clip_l.safetensors
```

Any ideas? BTW, running under `--cpu` mode works just fine(slooooooooow though).

![image](https://github.com/user-attachments/assets/3cdc3901-4311-4332-8031-5da9d351b4dc)

**Comment by city96** [comment]
@skelescene Are you also on apple hardware? That would likely make this specific to MacOS/MPS (possibly in cases where lowvram gets triggered)

**Comment by gorborukov** [comment]
Disabling --use-split-cross-attention (if enabled) can help

**Comment by Filarh** [comment]
ok now i'm seriously tired of this

![Image](https://github.com/user-attachments/assets/0f614b3a-2d3e-46d1-9d78-b9674cde5e97)

i've been the whole day swaping vaes, clips, etc
