### ISSUE TITLE
FP16 model recognized as FP8 by your GGUF converter

### ISSUE THREAD

**Issue by Foul-Tarnished** [city96/ComfyUI-GGUF#112]
Hi,

I used your GGUF converter in `tools` to get [this finetuned checkpoint](https://civitai.com/models/161068?modelVersionId=869391) to Q8_0.

This model has two files:
- "FP16" 11.08GB
- "BF16" 20.34GB

Afaik, FP16 and BF16 should have the same filesize, but it's not the case there, so I guess the uploader made a mistake, and the 11GB file is FP8 and the other is FP16/BF16.

**But the strange thing is both files are getting converted from `torch.float8_e4m3fn` by your tool !**

**Is this an error on the model author ?**
Maybe he finetuned a FP8 version of Flux.1 Dev but saved it as FP16/BF16, so that explains the missing precision ? Even then some precision should be gained from the finetune itself, so I don't think it's that

**Or is this an error on your converter ?**
Maybe letting us specify the input checkpoint floating point precision when using `converter.py` would help in this strange case ?

I'm not smart enough to analyze this model in details
Thanks for your help

**Comment by Foul-Tarnished** [comment]
Just looking at the files size and knowing the size of the official Flux.1 dev FP16 checkpoint, I can assume his 11GB file is definitely FP8.

But the second checkpoint, 20GB, is near the size of the FP16 original Flux.1 dev file, so it's really weird it's getting picked up as `float8_e4m3fn` and not FP16/BF16.

Maybe we have to manually check if the 20GB file last mantisses are just zeroed out, that would prove it's an issue on the model author side, saving useless data without added precision

**Comment by city96** [comment]
That's actually an fp8 model with an fp16 text encoder and a bf16 vae all mixed together. If you check it manually you'll see that the actual model part is fp8.

```
import torch
from safetensors.torch import load_file
sd = load_file("STOIQONewrealityFLUXSD_F1DPreAlpha.safetensors")
dt = [v.dtype for k,v in sd.items()]
ct = {x:dt.count(x) for x in set(dt)}
print(ct)
```
`{torch.float16: 416, torch.float8_e4m3fn: 780, torch.bfloat16: 244, torch.float32: 2}`

```
for k,v in sd.items():
    print(v.dtype, k)
```

![image](https://github.com/user-attachments/assets/27c88a22-38b5-4e16-90e7-1af276a485ee)

**Comment by Foul-Tarnished** [comment]
Oh I see, using your tool I only saw fp8 and nothing else iirc

Strange its still 20gb and the model part is only fp8

I'll ask the author if they can release a full fp16/bf16 version I guess

Thanks
