### ISSUE TITLE
Missing FluxGuidance

### ISSUE THREAD

**Issue by pystar1007** [city96/ComfyUI-GGUF#124]
![image](https://github.com/user-attachments/assets/6878aa43-d20d-40c9-8bc1-2ac4d57f3dc8)

**Comment by city96** [comment]
That's a ComfyUI default node that should be in the [base install](https://github.com/comfyanonymous/ComfyUI/blob/1b8089528502a881d0ed2918b2abd54441743dd0/comfy_extras/nodes_flux.py#L26) so unrelated to this node pack.

Update your ComfyUI or open an issue in the main repo.
