### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by trinhtuanvubk** [city96/ComfyUI-GGUF#125]
How can I infer this model straightforwardly, with a text input and an image output? I just want to run it normally
Thank you so much

**Comment by city96** [comment]
I think you would want to user diffusers for that, but AFAIK they don't have diffusers support (yet).

It's been requested in this repo here https://github.com/city96/ComfyUI-GGUF/issues/100 and Diffusers has an open issue about it here https://github.com/huggingface/diffusers/issues/9487 so I think you should follow those two issues for updates.

I wanted to work on something like that too but I've had zero free time lately :P
