### ISSUE TITLE
GGUF not working with aidock comfyui template

### ISSUE THREAD

**Issue by cubo94857** [city96/ComfyUI-GGUF#137]
I have also posted this on the ai dock github but havent gotten a response yet. I have tried many things to run a GGUF model but no matter what i do comfyui can not detect it. It can't detect the clip either. I've put the checkpoint and clip in the right place, downloaded the GGUF node, did what the github instructions said to do but it still cannot detect a GGUF. Regular flux dev and schnell work just fine, GGUF doesnt. This is on vast ai. Is there any chance you or anyone has a docker that works with GGUF?

**Comment by ibadmore** [comment]
did you find out what the issue was? GGUF models not showing up after i add them to unet folder

**Comment by cubo94857** [comment]
@ibadmore yes lol in my case it was because the file was named in random numbers instead of the actual name which is whatevertheactualnameis.safetensors
