### ISSUE TITLE
`newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead.

### ISSUE THREAD

**Issue by lelzhang** [city96/ComfyUI-GGUF#143]
When I use the flux1-schnell-Q4_K_S.gguf model, I encounter an error when it reaches the loader. “`newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead.”

**Comment by lelzhang** [comment]
![111](https://github.com/user-attachments/assets/098b4318-059d-4ef7-ac74-7626cace6522)

**Comment by city96** [comment]
See this issue for more info: https://github.com/city96/ComfyUI-GGUF/issues/7

TL;DR: For now, either downgrade numpy or apply the fix from that thread manually.
