### ISSUE TITLE
Unable to load GGUF t5xxl text_encoders

### ISSUE THREAD

**Issue by Polukeev** [city96/ComfyUI-GGUF#151]
After the Commit ee8abf0
https://github.com/comfyanonymous/ComfyUI/commit/ee8abf0cfff230286ac742138642c9876150f425

GGUF Clip loaders can't find any .gguf text encoders

**Comment by Thater** [comment]
ComfyUI changed the path for text encoders to models/text_encoders

you can change line 22 in node.py to 
`orig = folder_paths.folder_names_and_paths.get("text_encoders", [[], set()])`

and this will fix it

**Comment by Polukeev** [comment]
@Thater thank you for the solution! I hope @city96 will see this.

**Comment by city96** [comment]
Pushed a fix that should be backwards compatible as well (i.e. doesn't break on older comfy versions).
