### ISSUE TITLE
A few things to speed up inference on 8gb cards and keep them from OOMing with Q4

### ISSUE THREAD

**Issue by RandomGitUser321** [city96/ComfyUI-GGUF#16]
**EDIT: We got to the bottom of the issue**

Something about the latest update has destroyed performance on 8gb cards, when they were working fine before. For now, I've found adding `torch.cuda.empty_cache()` to the` def forward` in `ops.py` mitigates it somewhat. Before this update, I was getting ~3 sec/it, now, even with this hacky fix, it's still ~6-7 sec/it. If this isn't added, the iteration times will jump up exponentially into the 15-30 second range since it's spilling over into sysmem.

```
class GGMLOps(comfy.ops.disable_weight_init):
    """
    Dequantize weights on the fly before doing the compute
    """
    class Linear(GGMLLayer):
        def __init__(self, *args, device=None, dtype=None, **kwargs):
            super().__init__(device=device, dtype=dtype)
            self.parameters_manual_cast = torch.float32

        def forward(self, x):
            with torch.no_grad():
                weight, bias = self.get_weights(x.dtype)
                x = torch.nn.functional.linear(x, weight, bias)
                del weight, bias
                torch.cuda.empty_cache()
            return x
```

Also, it might be helpful to add an option to switch between fp16 and fp32. I did some testing and the image output was almost identical. Overall, you couldn't see a difference between them unless you arithmetically compared the two with image operations. If I set it to float16 here, instead of 32, it will cut inference times down from ~6.5 sec/it to 4.4 sec/it 

Within `dequant.py`
```
        else:
            # dequant in fp32, convert to target
            return dequantize(data, qtype, oshape, dtype=torch.float16).to(dtype)
```

A quick weird and high contrast image with only 20 steps(save me some time)
Float16:
![image](https://github.com/user-attachments/assets/8ebbc1f2-6225-49f7-a198-0952312525f5)
Float32:
![image](https://github.com/user-attachments/assets/e20946e9-7ef2-469d-be13-ec93c44886fe)
Here is the difference with an extremely low exponent value to blow out the differences:
![image](https://github.com/user-attachments/assets/bdd8df74-8f88-419d-8a1c-246e4ea6dff5)

**Comment by city96** [comment]
I was having most of the noticeable changes with Q8_0 via FP32 dequant VS FP16 casting, though it seemed more like a sidegrade. I'll run another test later this evening and possibly revert to (none) for the dequant and casting on return.

**Comment by city96** [comment]
Yeah, I don't think Q4_0 image quality actually changed after all. 

FP16 should be a no-op but could you see what happens if you use this:

```
return dequantize(data, qtype, oshape, dtype=None).to(dtype)
```

It might be faster while also solving the vram leak. I'm not too fond of spamming `torch.cuda.empty_cache()` inside a loop.

**Comment by city96** [comment]
Odd, seems like it's not cleaning up the intermediate values inside the dequant functions when it's doing them in FP32 for some reason. I don't think the safetensors thing is the same, though it could be that something similar to what you describe. i.e. it needs space for the intermediary values when unpacking them before quantizing it back down like you say.

Another thing you could try is to let it do BF16 directly via this version:

```
return dequantize(data, qtype, oshape, dtype=dtype)
```

**Comment by city96** [comment]
Ah right, if your card doesn't have bfloat then I think everything would be happening in FP16? That would explain at least some of what you're seeing as well as why the images in your tests were a lot more similar.

**Comment by GXcells** [comment]
> Ah right, if your card doesn't have bfloat then I think everything would be happening in FP16? That would explain at least some of what you're seeing as well as why the images in your tests were a lot more similar.

Is it normal that a T4 GPU cannot load the 4-bit quantized models?

**Comment by city96** [comment]
I changed it back for now, the increase in quality seemed more like a sidegrade even with BF16 according to most people and the increase in vram usage/possible memory leak is not worth it.

**Comment by city96** [comment]
I meant that for it already being in fp16 then doing `.to()` on it, which was still slowing it down. I guess checking the device/dtype adds some overhead. Anyway, closing this one for now.
