### ISSUE TITLE
LTXVideo "CLIPLoader (GGUF)" problem

### ISSUE THREAD

**Issue by Ratinod** [city96/ComfyUI-GGUF#163]
If you try to use "CLIPLoader (GGUF) type:ltxv" then some of the initial frames received will be broken.
"CLIPLoader (GGUF)":

https://github.com/user-attachments/assets/1bd34d6d-1701-4bc9-97c8-d42b2ef40233

"Load CLIP":

https://github.com/user-attachments/assets/ea881f3c-93a0-4756-b913-71492e5f393f

workflow used from here https://blog.comfy.org/ltxv-day-1-comfyui/
↓
![img](https://blog.comfy.org/content/images/2024/11/image-12.png)

gguf clip: https://huggingface.co/city96/t5-v1_1-xxl-encoder-gguf/blob/main/t5-v1_1-xxl-encoder-Q8_0.gguf

**Comment by whitespace-rebel** [comment]
I have the same problem that I described here:
https://github.com/comfyanonymous/ComfyUI/issues/5867

Also using the GGUF text encoder with the latest ComfyUI version is causing this error during ClLIP Text Encode:

CLIPTextEncode

'NoneType' object has no attribute 'model_size'

**Comment by city96** [comment]
Well, I haven't had the time to download LTXV to test, but I've pushed a fix that hopefully makes the clone logic less fragile (should make it work on latest comfy).

Don't think it fixes the first frame issue though, but might be worth a test?
(Also, if anyone has the time, could you check if the issue is still there if you load the FP16 `.safetensors` T5 file in the gguf clip loader? that might narrow it down)

**Comment by Ratinod** [comment]
> Well, I haven't had the time to download LTXV to test, but I've pushed a fix that hopefully makes the clone logic less fragile (should make it work on latest comfy).
> 
> Don't think it fixes the first frame issue though, but might be worth a test?

The output hasn't changed at all.

> (Also, if anyone has the time, could you check if the issue is still there if you load the FP16 `.safetensors` T5 file in the gguf clip loader? that might narrow it down)

CLIPLoader (GGUF) with "t5xxl_fp16.safetensors"(9.11gb) gives exactly the same output.

**Comment by city96** [comment]
Okay, I tested text2video, which didn't give me 1:1 results but it was close enough (i.e. no distortions).

I guess this only happens with img2video? Testing now lol.

**Comment by city96** [comment]
Actually, wait, from the example workflow they use a custom CLIP loader node that's defined [here](https://github.com/Lightricks/ComfyUI-LTXVideo/blob/366c43d7543f316607a69a84ed09f99a10bba209/t5_encoder.py).

![image](https://github.com/user-attachments/assets/4da3a853-bff6-4ac3-a16e-ecaa0cb13447)

That explains why it doesn't work. This node pack only extends the base ComfyUI Load CLIP node, so if you use the built-in Load CLIP you should get the same random artifacts, i.e. it's not just an issue with this node pack. Could you test if this is the case?

![image](https://github.com/user-attachments/assets/dcd7fc49-7a66-49bc-8d59-85024d091b44)

**Comment by Ratinod** [comment]
> Actually, wait, from the example workflow they use a custom CLIP loader node that's defined [here](https://github.com/Lightricks/ComfyUI-LTXVideo/blob/366c43d7543f316607a69a84ed09f99a10bba209/t5_encoder.py).
> 
> ![image](https://private-user-images.githubusercontent.com/125218114/392203923-4da3a853-bff6-4ac3-a16e-ecaa0cb13447.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMTUwNzksIm5iZiI6MTczMzMxNDc3OSwicGF0aCI6Ii8xMjUyMTgxMTQvMzkyMjAzOTIzLTRkYTNhODUzLWJmZjYtNGFjMy1hMTZlLWVjYWEwY2IxMzQ0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxMjE5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjU4N2EzYjg1ZDc5MWU4ZmIzYmI5MDdlMGIyMWZlMjYwNzM4NTcwZjFmZGVmZWQ0OTZjNjI5MWQ1MTQyMjBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RdUZFGPu7Hc3ztFXZDznN-rk5yG0FGyEXgZq_SMobsw)
> 
> That explains why it doesn't work. This node pack (ComfyUI-GGUF) only extends the base ComfyUI Load CLIP node, so if you use the built-in Load CLIP you should get the same random artifacts, i.e. it's not isolated to GGUF models.
> 
> Could you test if this is the case?
> 
> ![image](https://private-user-images.githubusercontent.com/125218114/392204629-dcd7fc49-7a66-49bc-8d59-85024d091b44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMTUwNzksIm5iZiI6MTczMzMxNDc3OSwicGF0aCI6Ii8xMjUyMTgxMTQvMzkyMjA0NjI5LWRjZDdmYzQ5LTdhNjYtNDliYy04ZDU5LTg1MDI0ZDA5MWI0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxMjE5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OGQ2Y2UxZDE2NDdlNjgyNDNkNjY2ODE5MjczOTBkZGVhMmNjYjA4Nzc4OTcwNWJhZGE2MWY3NzZmZmVhMzY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jbNcCssDQuOki4eopbaLM7q8hi7z9SZ6EkTBbxdC6t8)

As I show in the first message, I use the native implementation of LTXVideo.
I have NOT installed or used ComfyUI-LTXVideo nodes.
Workflow with native implementation of LTXVideo-> [Lightricks LTX-Video Model image-to-video | ComfyUI_examples](https://comfyanonymous.github.io/ComfyUI_examples/ltxv/?ref=blog.comfy.org#image-to-video)

If I use built-in "Load CLIP" with "[t5xxl_fp16.safetensors](https://huggingface.co/comfyanonymous/flux_text_encoders/blob/main/t5xxl_fp16.safetensors)" (not bf16 as you showed in the picture) I don't get artifacts.
If I use "CLIPLoader (GGUF)" with with "[t5xxl_fp16.safetensors](https://huggingface.co/comfyanonymous/flux_text_encoders/blob/main/t5xxl_fp16.safetensors)" I get artifacts.
If I use "CLIPLoader (GGUF)" with with "[t5-v1_1-xxl-encoder-Q8_0.gguf](https://huggingface.co/city96/t5-v1_1-xxl-encoder-gguf/blob/main/t5-v1_1-xxl-encoder-Q8_0.gguf)" I get artifacts.

**Comment by city96** [comment]
I'm a moron, should be fixed now.

**Comment by Ratinod** [comment]
I confirm it has been fixed.

**Comment by city96** [comment]
Apparently this was still happening in some cases, so I've attempted a more comprehensive fix.
