### ISSUE TITLE
Git version 2.47.0 deem patch files as corrupt

### ISSUE THREAD

**Issue by silveroxides** [city96/ComfyUI-GGUF#166]
Some change starting from version mentioned in title makes git not want to accept the lcpp.patch.

```
PS C:\Users\ishim\source\m\llama.cpp> git apply ..\lcpp.patch
error: corrupt patch at line 27
```

**Comment by city96** [comment]
Please see the comment in the readme for the tools folder. This is a common issue due to the line endings being changed during the git checkout.

>If you get a "corrupt patch" error, you may have to [change the line endings in the patch file](https://github.com/city96/ComfyUI-GGUF/issues/90#issuecomment-2323011648).
