### ISSUE TITLE
Missing node

### ISSUE THREAD

**Issue by SwannSchilling** [city96/ComfyUI-GGUF#17]
How do you force the CLIP to be allocated to your CUDA device, I cannot find the node!
Sorry for being such a noob...

**Comment by city96** [comment]
If you have a second GPU you can use [my one from here](https://gist.github.com/city96/30743dfdfe129b331b5676a79c3a8a39) or [this other one here](https://github.com/neuratech-ai/ComfyUI-MultiGPU) (haven't tested it)

**Comment by SwannSchilling** [comment]
Ahhhhh OK, thanks for the clarification!!
