### ISSUE TITLE
Unexpected architecture type in GGUF file, expected one of flux, sd1, sdxl, t5encoder but got 'hyvid'

### ISSUE THREAD

**Issue by ddddddeyrueuad** [city96/ComfyUI-GGUF#184]
when i use hunyuan-video-t2v-720p-Q4_0.gguf
![1734677918802](https://github.com/user-attachments/assets/dd7a6420-e685-4559-81a0-d4c6b9e6cb68)

Unexpected architecture type in GGUF file, expected one of flux, sd1, sdxl, t5encoder but got 'hyvid'

why？

**Comment by city96** [comment]
You need to update ComfyUI-GGUF to the latest version since model support was only added recently.
