### ISSUE TITLE
Clip Loaders dont work for sd3+ models anymore.

### ISSUE THREAD

**Issue by kseyhan** [city96/ComfyUI-GGUF#186]
The clip loaders only produce black output on my sd3+ workflows since some time. I tried moving the gguf files to the text_encoders directory like mentioned on some issues here and my files get picked up whether they are in the clip or the text_encoders folder. The clip loader does work without problems on the flux workflows too but all the sd3+ just dont. Whether i try to run them with the dual or the trippple clip loader. Exchanging the gguf clip loader for the one in the comfy core makes the workflows work again. No errors on the console are produced.

![Screenshot From 2024-12-22 15-41-04](https://github.com/user-attachments/assets/24024d9c-af3c-441e-9633-fe523dc6ce0b)

**Comment by city96** [comment]
Pushed a possible fix, could you verify if that fixes it?
