### ISSUE TITLE
[Features Request]: Kawai Kolors

### ISSUE THREAD

**Issue by Vigilence** [city96/ComfyUI-GGUF#19]
Would love to see [Kolors](https://huggingface.co/Kwai-Kolors/Kolors) supported.

**Comment by city96** [comment]
See comment here with reasoning: https://github.com/city96/ComfyUI-GGUF/issues/81#issuecomment-2319200811

Supporting models that aren't part of base ComfyUI would add a lot of overhead in this case. Of course, if it gets added to ComfyUI natively, I'll be adding support here too.
