### ISSUE TITLE
Dual clip loader with Hunyuan type ?

### ISSUE THREAD

**Issue by darkon12** [city96/ComfyUI-GGUF#190]
Will it be available the Hunyuan video option in type ?

EDIT: 
It is available. I must be blind.

**Comment by city96** [comment]
All good lol, it was added in this commit: https://github.com/city96/ComfyUI-GGUF/commit/8d1b56c5e2517219de12a01b742ed53cbaee463e

(The GGUF files for the LLaMA model are [here](https://huggingface.co/city96/llava-llama-3-8b-v1_1-imat-gguf))
