### ISSUE TITLE
sourceTensor.clone error

### ISSUE THREAD

**Issue by DominoUB** [city96/ComfyUI-GGUF#22]
Not sure if this is just me, but whenever I try to run a gguf (4, 5 or 8) I get the following error.
```
I\ComfyUI\custom_nodes\ComfyUI-GGUF\dequant.py:10: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  data = torch.tensor(tensor.data)
``` 
Then it just locks up and does nothing. 

My workflow
[gguf.json](https://github.com/user-attachments/files/16634118/gguf.json)

**Comment by city96** [comment]
This could be a few things, including package mismatch / running out of memory / loading very slowly from HDD (check your vram usage, is it slowly creeping up? It's mmap'ed so it only loads them on first use, which might take a while)

**Comment by DominoUB** [comment]
This is no longer an issue. I redownloaded the models and changed nothing else, and now it works. I'm assuming a corrupted model file.
