### ISSUE TITLE
'load_diffusion_model_state_dict

### ISSUE THREAD

**Issue by masterliu2021** [city96/ComfyUI-GGUF#23]
got prompt
[rgthree] Using rgthree's optimized recursive execution.
[rgthree]
 First run patching recursive_output_delete_if_changed and recursive_will_execute.
[rgthree] Note: If execution seems broken due to forward ComfyUI changes, you can disable the optimization from rgthree settings in ComfyUI.
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
Using xformers attention in VAE
Using xformers attention in VAE
D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-GGUF\ops.py:21: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:212.)
  data = torch.from_numpy(tensor.data)

ggml_sd_loader:
 GGMLQuantizationType.F16      476
 GGMLQuantizationType.Q4_0     304

!!! Exception during processing!!! module 'comfy.sd' has no attribute 'load_diffusion_model_state_dict'
Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.3\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\ComfyUI-aki-v1.3\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\ComfyUI-aki-v1.3\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-GGUF\nodes.py", line 51, in load_unet
    model = comfy.sd.load_diffusion_model_state_dict(
AttributeError: module 'comfy.sd' has no attribute 'load_diffusion_model_state_dict'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Prompt execu

Thanks sir, how can I solve this problem?

**Comment by Fannovel16** [comment]
Update ComfyUI

**Comment by city96** [comment]
As @Fannovel16 says above, you need to be on a recent enough version to support those changes - this is also mentioned in the readme:

>Make sure your ComfyUI is on a recent-enough version to support custom ops when loading the UNET-only.
