### ISSUE TITLE
Need to install sentencepiece

### ISSUE THREAD

**Issue by hben35096** [city96/ComfyUI-GGUF#24]

**Comment by city96** [comment]
[It's in the base ComfyUI requirements](https://github.com/comfyanonymous/ComfyUI/blob/05a9f3faa1ac4236705681cdf5f289267f4d3b9a/requirements.txt#L8). Not an issue with this custom node.

**Comment by hben35096** [comment]
Thank you, I made a mistake...

**Comment by city96** [comment]
No worries!
