### ISSUE TITLE
::| Running on 6GB V-Ram |::

### ISSUE THREAD

**Issue by kakachiex2** [city96/ComfyUI-GGUF#26]
Confirm running on RTX 260 6gb V-Ramm fast I'm surprised great works.
![workflow](https://github.com/user-attachments/assets/b484384a-3a5c-48ca-bacb-61f4f64c3707)

**Comment by city96** [comment]
I'm surprised people are managing to run this on 6GB and 8GB cards lol. In any case, enjoy!
