### ISSUE TITLE
trying to use lora loader, get ERROR lora diffusion_model.single_blocks.37.linear1.weight 'GGMLTensor' object has no attribute 'tensor_shape'

### ISSUE THREAD

**Issue by akedia** [city96/ComfyUI-GGUF#31]
![image](https://github.com/user-attachments/assets/17851c8b-8a5f-443d-acdb-1aa91aba6323)

**Comment by Nelathan** [comment]
i get a different error
`ERROR lora diffusion_model.double_blocks.18.img_attn.qkv.weight The size of tensor a (1728) must match the size of tensor b (3072) at non-singleton dimension 1
ERROR lora diffusion_model.double_blocks.18.img_attn.proj.weight The size of tensor a (1728) must match the size of tensor b (3072) at non-singleton dimension 1
ERROR lora diffusion_model.double_blocks.18.txt_attn.qkv.weight The size of tensor a (1728) must match the size of tensor b (3072) at non-singleton dimension 1
ERROR lora diffusion_model.double_blocks.18.txt_attn.proj.weight The size of tensor a (1728) must match the size of tensor b (3072) at non-singleton dimension 1`

**Comment by Danamir** [comment]
Got the same error :  

```
Loading 1 new model
ERROR lora diffusion_model.double_blocks.0.img_attn.qkv.weight 'GGMLTensor' object has no attribute 'tensor_shape'
ERROR lora diffusion_model.double_blocks.0.img_attn.qkv.weight 'GGMLTensor' object has no attribute 'tensor_shape'
ERROR lora diffusion_model.double_blocks.0.img_attn.qkv.weight 'GGMLTensor' object has no attribute 'tensor_shape'
ERROR lora diffusion_model.double_blocks.0.img_attn.proj.weight The size of tensor a (3264) must match the size of tensor b (3072) at non-singleton dimension 1
```

**Comment by cmcjas** [comment]
yeah same error as Danamir & Nelathan not sure if it's a problem with the version of pytorch we're using

**Comment by city96** [comment]
Should be fixed

**Comment by Danamir** [comment]
Fixed it for me too.

Sadly even without the errors, the LoRA has almost no effect the output, compared to the full model. I'll do a separate ticket.

**Comment by city96** [comment]
@Danamir sounds good, include a link to a LoRA if possible so I can test it.

**Comment by Nelathan** [comment]
works great now, only a 5% speed malus compared to no lora. Thank you! (used Q4_0 with FaeTasticDetails)

**Comment by cmcjas** [comment]
thansk for the fixed!
