### ISSUE TITLE
LoRA still giving "!!! Exception during processing !!! 'GGMLTensor' object has no attribute 'tensor_shape'"

### ISSUE THREAD

**Issue by danbradford7** [city96/ComfyUI-GGUF#37]
I know that a similar issue was fixed, but I am getting this error when trying to load a LoRA

![image](https://github.com/user-attachments/assets/52ed34a0-ae7a-4abf-bdfc-49877a618ca8)

**Comment by city96** [comment]
This happens completely randomly for some reason. Sometimes after restarting comfy it'll start working again and I have no idea why.

**Comment by danbradford7** [comment]
> This happens completely randomly for some reason. Sometimes after restarting comfy it'll start working again and I have no idea why.

I haven't been able to get it to run at all, I've tried multiple workflows as well

**Comment by marcuswilcour** [comment]
I had the same problem, and it turns out that when I stopped forcing the Dual CLIP to be loaded on the _cpu_ and instead loaded it on _cuda:0_, it worked.

**Comment by Talae06** [comment]
Same error, and setting the text encoders to be loaded on the GPU instead of the CPU (or entirely removing the "Force/Set CLIP device" node from the workflow) didn't change anything. Tried with my own workflow as well as [another one](https://civitai.com/models/632945/flux-lora-workflow-with-finetuneupscale) found on CIvitai. Both work fine when using the original full FP16.

**Comment by ahiser1117** [comment]
I think I have a solution @danbradford7 @city96 @marcuswilcour @Talae06.

It seems like sometimes the tensor_shape attribute is not being created. Might have to do with pytorch tensors not being mutable so this class is never being initialized. Either way, in the [ops.py file](https://github.com/city96/ComfyUI-GGUF/blob/main/ops.py) the shape method can be updated with a fall back:

```python
  @property
  def shape(self):
      if not hasattr(self, 'tensor_shape'):
          self.tensor_shape = self.size() 
      return self.tensor_shape
```

**Comment by city96** [comment]
@ahiser1117 Would that not result in casing errors if the real attribute (i.e. the real shape it should have) is stripped? i.e. we just move the problem of those attributes missing elsewhere.

**Comment by ahiser1117** [comment]
@city96 Yeah I was thinking the same, this seems to work as at least a temporary solution and LoRAs are loading for me.

**Comment by BenderFendor** [comment]
I was having a similar issue and fixed it by rolling back my comfyui to commit fca4283 as the update changed up the lora patcher

**Comment by Talae06** [comment]
@ahiser1117 Well, as a temporary fix at least, that worked for me, no error and the Lora is indeed applied correctly. Thanks !

**Comment by city96** [comment]
@ahiser1117 Thank you for the fix as well as testing it, I've added it to main.

**Comment by TripleHeadedMonkey** [comment]
Great work. Now it is possible to merge the weights of GGUF models with other formats too. That Shape Tensor error was the blocking point in that regard too.

However it is currently only usable in inference.

![image](https://github.com/user-attachments/assets/a1a095c9-4f7a-40fb-9f14-52da39555292)


When attempting to save the merged weights as either a GGUF or a standard Flux model I'm met with this new error though lol.

**Comment by caustiq** [comment]
> > This happens completely randomly for some reason. Sometimes after restarting comfy it'll start working again and I have no idea why.
> 
> I haven't been able to get it to run at all, I've tried multiple workflows as well

Same on 3060 12GB VRAM, 32GB sys RAM.
pytorch 2.4.0

**Comment by city96** [comment]
Closing since this shouldn't happen with the rewritten code anymore. Reopen if it still does by some chance.
