### ISSUE TITLE
ComfyUI renamed folder "unet" into "diffusion_models"

### ISSUE THREAD

**Issue by Danamir** [city96/ComfyUI-GGUF#39]
This https://github.com/comfyanonymous/ComfyUI/commit/4f7a3cb6fbd58d7546b3c76ec1f418a2650ed709 breaks the node loading, I think the only fix needed is to rename the dict entry, but you may want to add a check for backward compatibility.

```
Cannot import ComfyUI\custom_nodes\ComfyUI-GGUF module for custom nodes: 'unet'
```

**Comment by city96** [comment]
Fixed with fallback, now the .gguf files won't show up in the normal unet loader either lol.

**Comment by Danamir** [comment]
Nice, thanks.
