### ISSUE TITLE
ValueError: GGUF magic invalid

### ISSUE THREAD

**Issue by jyoung105** [city96/ComfyUI-GGUF#43]
Just wanna do on colab to inference quantized model as a camenduru's one.

But when I do below,
```
with torch.inference_mode():
    unet = UNETLoader.load_unet("flux1-dev-Q8_0.gguf")[0]
```

I got this error
```
[/content/ComfyUI/custom_nodes/quantized/nodes.py](https://localhost:8080/#) in load_unet(self, unet_name)
     60     def load_unet(self, unet_name):
     61         unet_path = folder_paths.get_full_path("unet", unet_name)
---> 62         sd = gguf_sd_loader(unet_path)
     63         model = comfy.sd.load_diffusion_model_state_dict(
     64             sd, model_options={"custom_operations": GGMLOps}

[/content/ComfyUI/custom_nodes/quantized/nodes.py](https://localhost:8080/#) in gguf_sd_loader(path)
     23     Read state dict as fake tensors
     24     """
---> 25     reader = gguf.GGUFReader(path)
     26     sd = {}
     27     dt = {}

[/usr/local/lib/python3.10/dist-packages/gguf/gguf_reader.py](https://localhost:8080/#) in __init__(self, path, mode)
     93         # Check for GGUF magic
     94         if self._get(offs, np.uint32, override_order = '<')[0] != GGUF_MAGIC:
---> 95             raise ValueError('GGUF magic invalid')
     96         offs += 4
     97 

ValueError: GGUF magic invalid
```

**Comment by city96** [comment]
This is most likely a corrupt model file / download. Try re-downloading it or re-convering it.

**Comment by jyoung105** [comment]
> This is most likely a corrupt model file / download. Try re-downloading it or re-convering it.

Thank you for your reply :)

I downloaded q8_0.gguf from your hf repo through aria2 module. Address was resolve/main/~.gguf for this error. But don't know why is it happened.

Ah the environment is .ipynb on colab btw.

**Comment by city96** [comment]
You could verify the file hash with `sha256sum` as a start. You can click the file on huggingface and it will show the hash there too.

![image](https://github.com/user-attachments/assets/91cb10e0-9f32-434c-ac13-809b9c78b6ea)

**Comment by jyoung105** [comment]
Thank you!
aria2 is not a good downloading module for hugging face I think.
after transform it to hf_hub_download, it works.
Thanks for telling me of SHA256!
