### ISSUE TITLE
KeyError: unet

### ISSUE THREAD

**Issue by homoluden** [city96/ComfyUI-GGUF#45]
After updating ComfyUI this module generates an import error because ComfyUI changed the folders structure.
On the screenshot below you can see the commented original line of code and next to it it is the fix.

![image](https://github.com/user-attachments/assets/0a784f1c-4df7-4af8-a6b7-9a1e9abc9c51)

**Comment by city96** [comment]
This has already been fixed to support both names, it looks like you're on an older version.

![image](https://github.com/user-attachments/assets/02e129d0-2bfc-4e3b-97e4-084dd4d8e70f)

**Comment by homoluden** [comment]
Hmmm strange. I tried to update many times using the Manager in ComfyUI. Let me check in CLI via direct git command.
Sorry for dup.
