### ISSUE TITLE
q4_k_m

### ISSUE THREAD

**Issue by al-swaiti** [city96/ComfyUI-GGUF#47]
hi ,,, thanks for this amazing job ,  adding the features of llama.cpp to sota models  is big step , i spent all night searching about this topic ,
Firstly  is there chance to make q4_k_m ,
secondly : T5 encoder already supported do u planing to convert it 
i,m waitin for view lines of codes to convert to Q8_K and others 
i think its already supported in gguf/quantise code 

![image](https://github.com/user-attachments/assets/ac9f497a-c912-48e1-9587-cf57b40b3c30)

**Comment by al-swaiti** [comment]
i'm tried to convert flux to K types , but , it give convert.py: error: Unknown quant/file type Q4_K 
can u help me to pypass this step , i'm already strugle inside codes !

**Comment by al-swaiti** [comment]
![image](https://github.com/user-attachments/assets/eebcb3da-bede-41ad-b53f-46341aac1506)
do i need to wait for llama-cpp update !

**Comment by city96** [comment]
@al-swaiti Again, re-read the original comment and be patient.
>The K quants need C++ code to quantize and my solution to generate the current ones is really hacky,
>I'll upload it as a diff from the original llama.cpp repo once I'm done with everything else.

Specifically this part:
> **once I'm done with everything else.**

**Comment by al-swaiti** [comment]
thank you

**Comment by city96** [comment]
@RandomGitUser321 First version of GGUF text encoder is up, check https://github.com/city96/ComfyUI-GGUF/pull/49 for more info

**Comment by JorgeR81** [comment]
The T5 Q8_0 is working fine for me. 

Similar size, but better results than T5 FP8.

Didn't tried the T5 q4_k_m, but may usefull if you only have 16GB RAM

**Comment by city96** [comment]
Updated instruction with patch, see updated readme in the [tools](https://github.com/city96/ComfyUI-GGUF/tree/main/tools) folder.

**Comment by al-swaiti** [comment]
THANK YOU TO MUCH I ALREADY QUANTIZED 3 MODEL ,,,, 
REACH HERE 
./llama.cpp/build/bin/llama-quantize  Stable-diffusion/mege-BF16.gguf q4ks.gguf
 IQ1_M

🤣
==========================================================================================================
Please do not use IQ1_S, IQ1_M, IQ2_S, IQ2_XXS, IQ2_XS or Q2_K_S quantization without an importance matrix ANY IDEA !

**Comment by city96** [comment]
It says right there, those quantization types are unusable without an imatrix. Don't make IQ quants either they won't work in ComfyUI.

**Comment by al-swaiti** [comment]
@city96  your opinion is very important , this is my special merge (coding)
https://civitai.com/models/682369?modelVersionId=764918
thanks

**Comment by city96** [comment]
@al-swaiti Seems to work fine. I've looked at Q4_K_M and the keys are all in the right format, and looks like the _M logic worked with some being in Q4_K and some other keys in Q5_K as intended. Two things to nitpick:

- "Q_8" as you named it isn't a quantization. It should be called "Q8_0".
- I think the license needs to be the same as the dev model if you used any part of the dev model instead of just "Apache2"

Other than that it looks good to me, output is perfectly coherent. Thank you for following the guide and not disabling any of the key checks/messing with the format lol.

**Comment by al-swaiti** [comment]
@city96 
okay ,,, about license i think you already know the flux dev is aura flow model  trained on better quality dataset , is there any part of the model showed using of dev!? , 
* here i was trying another way of quantization ,, but i struggled 
could i apply it for normal comfyui models ?
https://gist.github.com/sayakpaul/e1f28e86d0756d587c0b898c73822c47

**Comment by city96** [comment]
>okay ,,, about license i think you already know the flux dev is aura flow model trained on better quality dataset , is there any part of the model showed using of dev!? ,

I'm not sure what you're saying here. Are you claiming you've merged AuraFlow with Flux1-schnell?

>could i apply it for normal comfyui models ?

You could implement it as a custom node but windows support would most likely need extra work based on just the comments there. As this is a different quantization method, it's also out of scope for this repository/issues and you should do your own research on this topic.
