### ISSUE TITLE
Add ControlNet support

### ISSUE THREAD

**Issue by JorgeR81** [city96/ComfyUI-GGUF#51]
This does not work with Xlabs ControlNet.

There is no error. 
It just gets stuck in the KSampler node, before even starting to generate, but GPU usage is very high. 

This may be a Comfy UI issue, because I have the exact same problem, when using the default UNET loader.
https://github.com/comfyanonymous/ComfyUI/issues/4482

ControlNet only works using the Comfy UI checkpoint version of Flux.

**Comment by al-swaiti** [comment]
i try it it's  supported , 
![image](https://github.com/user-attachments/assets/d5e73449-6ede-48de-8545-205378b3dee1)
but the xlab publish weak workflow 
![image](https://github.com/user-attachments/assets/21ab5fce-1394-4658-99d0-5317e97eb054)
try to drop this image to your comfyui , or download the workflow https://civitai.com/models/704488/controlnetfluxgguf
also ipadapter work perfect with gguf 
![image](https://github.com/user-attachments/assets/1a7ad0c7-8bab-4d36-8a82-44051a8478f2)
hers the workflow 
https://civitai.com/models/703833/ipadapter

**Comment by JorgeR81** [comment]
Yeah, you're right. (  I forgot to close this ).
It also works without the Xlabs custom nodes.
It started working, around the time the UNET loader issue got fixed, in Comfy UI.
