### ISSUE TITLE
Flux output is blurry compared to webui-forge

### ISSUE THREAD

**Issue by Foul-Tarnished** [city96/ComfyUI-GGUF#54]
I made a gen on Forge and on ComfyUI with your extension, and it seems it's blurrier on Comfy

I use this workflow (https://comfyanonymous.github.io/ComfyUI_examples/flux/)
but with your extension (Q6_K and t5xxl fp8 models)

**I tried to replicate a gen on forge to compare, and it seems it's not just a model/prompt issue:**

ComfyUI
<img src="https://github.com/user-attachments/assets/9f2d92d4-978c-44b4-8242-2dc85cb298f6" width="50%"/>

SDWebUI-Forge
<img src="https://github.com/user-attachments/assets/c079f8e5-b323-400e-af22-2fff302870cc" width="50%"/>

It's strange because half the generations are blurry on both (model/prompt issue) but if I replicate, comfy does appear blurrier, **always**.
This one is already blurry, but even some better prompts, still are blurrier on comfyui than forge

### Other

- Fresh ComfyUI standalone install, then upgraded to Pytorch 12.4, on RTX 4080
- I tried everything I could think of to replicate (CPU noise on forge, same sampling method and schedule type, same sampling steps)
- Could be an issue on ComfyUI itself, as I didn't check if FP8/FP16 has this issue

**Comment by Foul-Tarnished** [comment]
> What are your sampler and scheduler settings? Also, is forge set to emulate comfyui? (settings->compatability->comfyui, not sure if it matters here though but it might)
> 
> To me, it looks like when a noise schedule is missing the last step or something like sgm_uniform vs ddim_uniform: 

Euler, beta, 30 steps (you can see in the metadata of the pictures)

I dit not enable the comfyUI compat thing in forge though

**Comment by city96** [comment]
@Foul-Tarnished Could you try and reproduce this with the default FP16 model and just the built in nodes? It'll be slow but it should still work for a single image.

I suspect that this is an issue with ComfyUI/your workflow and not this node specifically.

**Comment by al-swaiti** [comment]
try [8d1fbbc](https://github.com/city96/ComfyUI-GGUF/commit/8d1fbbc456d50fe340bbbd775cefea79a5ed8835) firstly to compare any model , did you use same model in both !!!
Q6_K work in forge !
if you want to campare result use Q8 the most  closed to fp16 and better than fp8

**Comment by Foul-Tarnished** [comment]
I am not asking for recommendations about which quantized variant to run.

**Comment by TripleHeadedMonkey** [comment]
Hey there. It's possible in Comfy this is due to the "model sampling flux" node not being present.

![ComfyUI_63680_](https://github.com/user-attachments/assets/6a65c975-a852-4bc5-a7f8-0437da9be8c3)

Above is using model sampling resolution 2048 and below is using model sampling resolution 512 or so.

![ComfyUI_63681_](https://github.com/user-attachments/assets/b35edfb4-c890-48a8-a595-dfcd8aa4a5ef)

This is unfortunately a setting which seems to impact GGUF and NF4 versions of models in a way that doesn't seem to be as controllable, or perhaps the nature of the formats themselves simply add something else similar on top.

Sorry if this isn't helpful at all.

![image](https://github.com/user-attachments/assets/20f15c13-7034-458b-99e1-a1a052b68ad3)

**Comment by Foul-Tarnished** [comment]
Thanks for the useful insight

I used the workflow from comfy wiki, I don't remember the exact nodes it
has, but there was one that said it adapt the noise based on the resolution
of the image.

I tried to bypass it and the result was similar

**Comment by TripleHeadedMonkey** [comment]
In my experiments the lower the value the better for fine detail, however once you reach around 128x128 it basically doesn't change any more.

**Comment by city96** [comment]
This could be related: https://github.com/city96/ComfyUI-GGUF/issues/46
