### ISSUE TITLE
Error occurred when executing DualCLIPLoaderGGUF:

### ISSUE THREAD

**Issue by kakachiex2** [city96/ComfyUI-GGUF#56]
I'm getting this errors message wen loading the dual clip Gguf loader, im using the t5-v1_1-xxl-encoder-Q5_K_M.gguf

Error occurred when executing DualCLIPLoaderGGUF:

module 'comfy.sd' has no attribute 'load_text_encoder_state_dicts'

File "K:\ComfyUI\ComfyUI\execution.py", line 316, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI\execution.py", line 191, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI\execution.py", line 168, in _map_node_over_list
process_inputs(input_dict, i)
File "K:\ComfyUI\ComfyUI\execution.py", line 157, in process_inputs
results.append(getattr(obj, func)(**inputs))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 224, in load_clip
return (self.load_patcher(clip_paths, clip_type, self.load_data(clip_paths)),)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 183, in load_patcher
clip = comfy.sd.load_text_encoder_state_dicts(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by a-ru2016** [comment]
Please update comfyUI.

**Comment by kakachiex2** [comment]
It works thanks bro
