### ISSUE TITLE
Linux Support?

### ISSUE THREAD

**Issue by Elektroney** [city96/ComfyUI-GGUF#61]
Maybe I'm just too dumb, but i cant get this running on Linux and its clearly made for windows, Instruction for Linux Users would be nice!

## Install Logs 

(venv) tron@tron-MS-7978:~/Downloads$ git clone https://github.com/city96/ComfyUI-GGUF ComfyUI/custom_nodes/ComfyUI-GGUF

.\python_embeded\python.exe -s -m pip install -r .\ComfyUI\custom_nodes\ComfyUI-GGUF\requirements.txt
Cloning into 'ComfyUI/custom_nodes/ComfyUI-GGUF'...
remote: Enumerating objects: 130, done.
remote: Counting objects: 100% (72/72), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 130 (delta 55), reused 43 (delta 34), pack-reused 58 (from 1)
Receiving objects: 100% (130/130), 47.92 KiB | 2.28 MiB/s, done.
Resolving deltas: 100% (69/69), done.
.python_embededpython.exe: command not found
(venv) tron@tron-MS-7978:~/Downloads$ git clone https://github.com/city96/ComfyUI-GGUF ComfyUI/custom_nodes/ComfyUI-GGUF

.\python_embeded\python.exe -s -m pip install -r .\ComfyUI\custom_nodes\ComfyUI-GGUF\requirements.txt

fatal: destination path 'ComfyUI/custom_nodes/ComfyUI-GGUF' already exists and is not an empty directory.
.python_embededpython.exe: command not found

## Run Logs (After manually installing)

tron@tron-MS-7978:~/Downloads/ComfyUI-master$ python main.py

Total VRAM 1996 MB, total RAM 28021 MB
pytorch version: 2.4.0+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 950 : native
Using pytorch cross attention

Traceback (most recent call last):
  File "/home/tron/Downloads/ComfyUI-master/main.py", line 86, in <module>
    import execution
  File "/home/tron/Downloads/ComfyUI-master/execution.py", line 13, in <module>
    import nodes
  File "/home/tron/Downloads/ComfyUI-master/nodes.py", line 14, in <module>
    from .ops import GGMLTensor, GGMLOps

ImportError: attempted relative import with no known parent package

**Comment by city96** [comment]
Yeah, the instructions are for windows, sorry about that lol.

>File "/home/tron/Downloads/ComfyUI-master/nodes.py", line 14, in
from .ops import GGMLTensor, GGMLOps

This looks like you cloned it directly into the main ComfyUI folder instead of the custom nodes folder and overwrote the default nodes.py somehow. You may have to re-clone ComfyUI to fix that. Made the readme less confusing so hopefully this won't happen to other people.


For a manual installation, you should probably do it like this (run these one after the other)

```
cd /home/tron/Downloads/ComfyUI-master/custom_nodes/
git clone https://github.com/city96/ComfyUI-GGUF
cd ComfyUI-GGUF
pip install -r requirements.txt
```

**Comment by al-swaiti** [comment]
keep in mind exe type is just for windows @Elektroney

**Comment by Elektroney** [comment]
> keep in mind exe type is just for windows @Elektroney 

Haha yea im aware. Issue is resolved thanks a lot
