### ISSUE TITLE
Linear' object has no attribute 'out_features'

### ISSUE THREAD

**Issue by XTRMsavage** [city96/ComfyUI-GGUF#62]
When I try to use the flux1-dev-Q4_0.gguf model I am getting this error.

**Comment by Arron17** [comment]
You aren't trying to use it with the IPAdapter nodes from https://github.com/XLabs-AI/x-flux-comfyui are you?

As GGUF Models aren't supported and that's the exact error you get if you try.

**Comment by city96** [comment]
It looks like the xlabs repo fixed this based on the linked issue? I'll close this but reopen if not.

We also refactored ops.py since so in theory models that rely on the "out_features" attribute like that should be able to work without changes.
