### ISSUE TITLE
numpy version

### ISSUE THREAD

**Issue by gsm1258** [city96/ComfyUI-GGUF#67]
ComfyUI_windows_portable_nvidia_or_cpu_nightly_pytorch.7z , numpy is 2.1.0
ComfyUI-GGUf‘s numpy is 1.26.4.
Please upgrade to the new version of numpy as soon as possible to maintain consistency. Thank you.

**Comment by city96** [comment]
Not possible at the moment due to gguf requiring numpy<2.0.0 - see this issue / the linked llama.cpp issue in this thread https://github.com/city96/ComfyUI-GGUF/issues/7
