### ISSUE TITLE
hyper is not compatible to GGUF model!!

### ISSUE THREAD

**Issue by kiron111** [city96/ComfyUI-GGUF#75]
Bytedances: 8-steps and 16-steps FLUX.1-dev-related LoRAs are available now
I just tried the 8-steps hyper lora to GGUF...seems it's not compatible

**Comment by al-swaiti** [comment]
i think you have to ask the "hyper profider to support it"

**Comment by kiron111** [comment]
after I upgrade the comfyui and this node, seems the hyper lora is supported
I don't know why, some lora loader node is no effect

and now seems the lora has effect on, but the cmd does not show any log of loading of lora (no matter it's success or not)

**Comment by al-swaiti** [comment]
is Q lora supported ?@kiron

**Comment by kiron111** [comment]
> Q lora

you mean does flux1-dev-bnb-nf4 support LORA?
or it means other thing?

All I heard is the nf4 models do not support lora yet, coz I use GGUF only, I cannot tell if the current situation.

**Comment by city96** [comment]
What issues are you seeing? Not sure if relevant but it does say this in the description:

![image](https://github.com/user-attachments/assets/aba9587e-b2e1-4c41-9773-b254fa4e0a4b)

With that set it does sample for me at least.

**Comment by JorgeR81** [comment]
Yes, the 8 step lora it's working for me, without errors.

The FP8 results are similar to Q4_K_S in terms of quality ( although not as good as a normal 20 step generation ).

With the Q8_0, the images are a bit less "finished", using only 8 steps.
I think that's because of this: https://github.com/city96/ComfyUI-GGUF/issues/33

**Comment by patientx** [comment]
> Yes, the 8 step lora it's working for me, without errors.
> 
> The FP8 results are similar to Q4_K_S in terms of quality ( although not as good as a normal 20 step generation ).
> 
> With the Q8_0, the images are a bit less "finished", using only 8 steps. I think that's because of this: #33

can you share the workflow with the lora ?

**Comment by JorgeR81** [comment]
> Can you share the workflow with the lora ?

You can use the [ LoraLoaderModelOnly ] node.

The model creator recommends a strength of 0.125 
https://huggingface.co/ByteDance/Hyper-SD

The issue with the Q8_0 model was fixed.

**Comment by city96** [comment]
Closing since I \*think\* this should work on latest without issues? Reopen if not.
