### ISSUE TITLE
Where can I find it?Force/Set CLIP Device

### ISSUE THREAD

**Issue by jokero3answer** [city96/ComfyUI-GGUF#82]

**Comment by jokero3answer** [comment]
@city96

**Comment by city96** [comment]
Assuming you've read the disclaimer of not using it to put it on cuda:0 (so either cuda:1 if you have 2 GPUs or cpu if you want to force the text encoder) - [here](https://gist.github.com/city96/30743dfdfe129b331b5676a79c3a8a39)

**Comment by jokero3answer** [comment]
extremely grateful
