### ISSUE TITLE
Can't convert fp16 to GGUF using Tool

### ISSUE THREAD

**Issue by wardensc2** [city96/ComfyUI-GGUF#90]
Hi @city96 

I stuck after convert file to fp16. Everytime I try to run the lccp.patch I get these error: "error: corrupt patch at line 27"

![image](https://github.com/user-attachments/assets/6459401f-be7d-463d-9a16-f7f12c30c259)

Please help me to fix this. Thank you so much

**Comment by city96** [comment]
I suspect your git clone may have changed the line endings from the linux ones to windows ones. If you have notepad++ installed you should be able to change them like this (bottom right corner)

![image](https://github.com/user-attachments/assets/7bd672b7-a0c5-4989-a332-b59aa02f6355)
