### ISSUE TITLE
error: corrupt patch at line 27

### ISSUE THREAD

**Issue by drago87** [city96/ComfyUI-GGUF#91]
Following this https://github.com/city96/ComfyUI-GGUF/tree/main/tools
I get a `error: corrupt patch at line 27` when running the command `git apply ..\lcpp.patch` 

As for when i run `python convert.py --src model` is it meant to create a GGUF file in the same folder as the safetensor file?

**Comment by city96** [comment]
For the patch, see here: https://github.com/city96/ComfyUI-GGUF/issues/90#issuecomment-2323011648 - not sure if the fix works but it seems to be the same issue so let's track in there.

>is it meant to create a GGUF file in the same folder as the safetensor file?

Yes unless you specify `--dst`

**Comment by drago87** [comment]
For me it did not make a GGUF file and i got no error

**Comment by city96** [comment]
I guess if you run out of system memory it might crash to console with no error. How far did it get when you ran `convert.py`? i.e. what was the last message it printed out.

**Comment by drago87** [comment]
System memory was a problem as it did nothing for a second or two and then went back asking for inputs.

After a restart this is what i get
```
Architecture detected from input: flux
  0%|                                                                                          | 0/780 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\AI\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-GGUF\tools\convert.py", line 192, in <module>
    handle_tensors(path, writer, state_dict)
  File "D:\AI\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-GGUF\tools\convert.py", line 113, in handle_tensors
    data = data.numpy()
           ^^^^^^^^^^^^
TypeError: Got unsupported ScalarType Float8_e4m3fn
```

**Comment by city96** [comment]
Pushed a fix. That checkpoint seems to be in FP8 while the conversion requires FP16 (gguf/numpy can't handle FP8 afaik). Now it's just converted on the fly.

**Comment by drago87** [comment]
That seams to have fixed it. Atleast now it's working on the file.
