### ISSUE TITLE
Recent OPS refactor PR causes memory issues with --lowvram/--disable-smart-memory

### ISSUE THREAD

**Issue by RandomGitUser321** [city96/ComfyUI-GGUF#93]
It will cause the models to consume a lot more system memory. With a basic workflow using Flux Q8_0 and T5 Q5_K_M, I'm sitting at 28.8gb/32gb after inference.

More info in https://github.com/city96/ComfyUI-GGUF/pull/92

**Comment by city96** [comment]
Closing this since it's technically fixed, though there's still a spike during the initial load on windows.
