### ISSUE TITLE
Extreme loss of speed when batching generations after recent updates

### ISSUE THREAD

**Issue by Silanda** [city96/ComfyUI-GGUF#94]
I'll preface by saying that I updated the GGUF loader and ComfyUI at the same time, so I'm not 100% sure which is to blame.

Since updating on September 3rd, generations have become extremely slow, but I have a suspicion as to why. FWIW, I always use a batch size of 3 as batching offers a reasonable speed boost. It's gone from <5 s/it to around 30 s/it.

I use the Q8 version of the Flux model, but that doesn't fit completely into my 12GB of VRAM, and the FP16 version of the text encoder, which does fit into VRAM. 

My interpretation of the previous behaviour is that after processing the prompt, the text encoders would be kicked out of VRAM and the Flux model loaded partially in. I'm not sure that the encoders are being kicked out any more.  I'm getting this in the console before generation begins. Also, GPU power usage is low during generations, suggesting to me that it's mainly accessing the model from system RAM:

ggml_sd_loader:
 GGMLQuantizationType.F16      476
 GGMLQuantizationType.Q8_0     304
got prompt
model weight dtype torch.bfloat16, manual cast: None
model_type FLUX
clip missing: ['text_projection.weight']
Requested to load FluxClipModel_
Loading 1 new model
loaded completely 0.0 9320.35888671875 True
Requested to load Flux
Loading 1 new model
loaded partially 174.04657440185542 173.736328125 0

There are two way that I can mitigate this: I can either use the --disable-smart-memory command line switch, or I can use the Force/Set CLIP Device node to run it from CPU. In any case, this didn't used to be necessary.

**Comment by Silanda** [comment]
Ah! I think it's the GGUF clip loader.

Even though I was using the standard FP16 text encoder, I was using the GGUF dual clip loader to give me the option of using the quantized models if need be. 

If I use the standard Comfy Dual Clip Loader, this problem does not seem to occur.

**Comment by city96** [comment]
Yeah, the LoRA weight fix seems to mess with model management. I've reverted that part temporarily until a better solution is found. Updating should get you back to the normal behavior.
